#!/usr/bin/python3
import sys
sys.path.insert(0, "..")
import minimoul

main = """
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

char	*ft_strcat(char *dest, char *src);

int main(int argc, char **argv)
{
	char buf1[100];

    (void)argc;
	strcpy(buf1, argv[1]);
    printf("%s", ft_strcat(buf1, argv[2]));
}
"""

from random import randint, choice

alpha = "abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
test_list = []
for i in range(30):
	s = '"'
	for j in range(2):
		for k in range(randint(0, 10)):
			s += choice(alpha)
		s += '" "'
	test_list.append(s + '"')
test_list += ['"" ""', '"un" "mot"', '"" "aaa"']

minimoul.do_test("ft_strcat.c", main, test_list)
