#!/usr/bin/python3
import sys
sys.path.insert(0, "..")
import minimoul

from random import randint, choices

alpha = "abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ       "
test_list = [" ".join(choices(['"' + "".join(choices(alpha, k=randint(5, 15))) +  '"' for j in range(7)], k=randint(0, 6))) for i in range(25)]
test_list += ['', '""', '"unmot"']


minimoul.do_test("count_words.c", None, test_list)
