#!/usr/bin/python3
import sys
sys.path.insert(0, "..")
import minimoul

main = """
#include <stdlib.h>
#include <unistd.h>

char	*ft_strncpy(char *dest, char *src, unsigned int n);

int main(int argc, char **argv)
{
	char	buf[100];
    (void)argc;
    write(1, ft_strncpy(buf, argv[1], atoi(argv[2])), atoi(argv[2]));
}
"""

from random import randint, choice

alpha = "abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
test_list = []
for i in range(30):
	s = '"'
	for j in range(randint(2, 12)):
		for k in range(randint(0, 10)):
			s += choice(alpha)
		s += " "
	test_list.append(s + '" ' + str(max(0, len(s) + randint(-3, 3))))
test_list += ['"" 2']

minimoul.do_test("ft_strncmp.c", main, test_list)
