#!/usr/bin/python3
import sys
sys.path.insert(0, "..")
import minimoul

main = """
#include <stdlib.h>
#include <stdio.h>

void	ft_putnbr(int nbr);

int main(int argc, char **argv)
{
    (void)argc;
    ft_putnbr(atoi(argv[1]));
}
"""

from random import randint

test_list = [str(randint(-2147483648, 2147483647)) for i in range(30)]
test_list += ["0", "-2147483648", "2147483647"]

minimoul.do_test("ft_putnbr.c", main, test_list)
